// Copyright Eli Arbel (no explicit copyright notice in original file)

// Originated from: RoslynPad, RoslynPad.Roslyn, Completion/Glyph.cs

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Altaxo.CodeEditing.Completion
{
	public enum Glyph
	{
		None,
		Assembly,
		BasicFile,
		BasicProject,
		ClassPublic,
		ClassProtected,
		ClassPrivate,
		ClassInternal,
		CSharpFile,
		CSharpProject,
		ConstantPublic,
		ConstantProtected,
		ConstantPrivate,
		ConstantInternal,
		DelegatePublic,
		DelegateProtected,
		DelegatePrivate,
		DelegateInternal,
		EnumPublic,
		EnumProtected,
		EnumPrivate,
		EnumInternal,
		EnumMember,
		Error,
		StatusInformation,
		EventPublic,
		EventProtected,
		EventPrivate,
		EventInternal,
		ExtensionMethodPublic,
		ExtensionMethodProtected,
		ExtensionMethodPrivate,
		ExtensionMethodInternal,
		FieldPublic,
		FieldProtected,
		FieldPrivate,
		FieldInternal,
		InterfacePublic,
		InterfaceProtected,
		InterfacePrivate,
		InterfaceInternal,
		Intrinsic,
		Keyword,
		Label,
		Local,
		Namespace,
		MethodPublic,
		MethodProtected,
		MethodPrivate,
		MethodInternal,
		ModulePublic,
		ModuleProtected,
		ModulePrivate,
		ModuleInternal,
		OpenFolder,
		Operator,
		Parameter,
		PropertyPublic,
		PropertyProtected,
		PropertyPrivate,
		PropertyInternal,
		RangeVariable,
		Reference,
		StructurePublic,
		StructureProtected,
		StructurePrivate,
		StructureInternal,
		TypeParameter,
		Snippet,
		CompletionWarning,
		AddReference,
		NuGet,
	}
}